"""Aggiunta data_richiesta a Trasferta

Revision ID: 08f0abc6937f
Revises: bdcab2c60270
Create Date: 2025-12-15 20:47:11.752474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f0abc6937f'
down_revision = 'bdcab2c60270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_richiesta', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('data_richiesta')

    # ### end Alembic commands ###
