"""add struttura to dipendente

Revision ID: 106293122911
Revises: ab09b6a6991b
Create Date: 2026-09-24 10:22:21.966010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106293122911'
down_revision = 'ab09b6a6991b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dipendente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('struttura', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dipendente', schema=None) as batch_op:
        batch_op.drop_column('struttura')

    # ### end Alembic commands ###
