"""Aggiunta tabella Spesa e campo richiesta rimborso

Revision ID: 1f21ed5e7f69
Revises: fdc3a694d7f2
Create Date: 2025-12-14 09:24:15.845455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f21ed5e7f69'
down_revision = 'fdc3a694d7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_trasferta', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('data_spesa', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_trasferta'], ['trasferta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('trasferta', schema=None) as batch_op:
            batch_op.add_column(sa.Column('data_richiesta_rimborso', sa.DateTime(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('data_richiesta_rimborso')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spesa')
    # ### end Alembic commands ###
