"""Add presenze columns

Revision ID: 1f5f1a0efab1
Revises: 87c937a307f7
Create Date: 2025-12-16 19:02:28.772760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5f1a0efab1'
down_revision = '87c937a307f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gestito_presenze', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nbp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('nbp')
        batch_op.drop_column('gestito_presenze')

    # ### end Alembic commands ###
