"""Creazione dello schema iniziale completo

Revision ID: 29ab524c8a6f
Revises: 940d51ebafff
Create Date: 2025-12-13 16:19:36.211781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ab524c8a6f'
down_revision = '940d51ebafff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_premissione', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note_rendicontazione', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rapporto_finale', sa.Text(), nullable=True))
        batch_op.alter_column('missione_presso',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.alter_column('missione_presso',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('rapporto_finale')
        batch_op.drop_column('note_rendicontazione')
        batch_op.drop_column('note_premissione')

    # ### end Alembic commands ###
