"""increase utilizzo_mezzo length

Revision ID: 87c937a307f7
Revises: 08f0abc6937f
Create Date: 2025-12-16 17:26:40.910053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c937a307f7'
down_revision = '08f0abc6937f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.alter_column('utilizzo_mezzo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.alter_column('utilizzo_mezzo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
