"""Aggiunta colonna note_approvazione_post al modello Trasferta

Revision ID: 8958e28f86eb
Revises: 1f21ed5e7f69
Create Date: 2025-12-14 17:17:28.524550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8958e28f86eb'
down_revision = '1f21ed5e7f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('data_richiesta_rimborso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_richiesta_rimborso', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
