"""Creazione iniziale dello schema con tutti i campi

Revision ID: 940d51ebafff
Revises: 
Create Date: 2025-12-13 12:56:01.746219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940d51ebafff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dipendente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('ruolo', sa.String(length=50), nullable=False),
    sa.Column('id_dirigente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dirigente'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('delega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_delegante', sa.Integer(), nullable=False),
    sa.Column('id_delegato', sa.Integer(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_delegante'], ['dipendente.id'], ),
    sa.ForeignKeyConstraint(['id_delegato'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trasferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giorno_missione', sa.Date(), nullable=False),
    sa.Column('inizio_missione_ora', sa.Time(), nullable=True),
    sa.Column('missione_presso', sa.String(length=100), nullable=False),
    sa.Column('motivo_missione', sa.Text(), nullable=True),
    sa.Column('utilizzo_mezzo', sa.String(length=10), nullable=True),
    sa.Column('aut_extra_orario', sa.String(length=10), nullable=True),
    sa.Column('aut_timbratura_entrata', sa.Time(), nullable=True),
    sa.Column('aut_timbratura_uscita', sa.Time(), nullable=True),
    sa.Column('motivo_timbratura', sa.Text(), nullable=True),
    sa.Column('temp_colonna', sa.String(length=10), nullable=True),
    sa.Column('ora_inizio_effettiva', sa.Time(), nullable=True),
    sa.Column('ora_fine_effettiva', sa.Time(), nullable=True),
    sa.Column('durata_totale_ore', sa.Integer(), nullable=True),
    sa.Column('pernotto', sa.Boolean(), nullable=True),
    sa.Column('durata_viaggio_andata_min', sa.Integer(), nullable=True),
    sa.Column('durata_viaggio_ritorno_min', sa.Integer(), nullable=True),
    sa.Column('km_percorsi', sa.Float(), nullable=True),
    sa.Column('mezzo_km_percorsi', sa.String(length=50), nullable=True),
    sa.Column('percorso_effettuato', sa.Text(), nullable=True),
    sa.Column('richiesta_pausa_pranzo', sa.String(length=50), nullable=True),
    sa.Column('pausa_pranzo_dalle', sa.Time(), nullable=True),
    sa.Column('pausa_pranzo_alle', sa.Time(), nullable=True),
    sa.Column('extra_orario', sa.String(length=50), nullable=True),
    sa.Column('stato_post_missione', sa.String(length=50), nullable=False),
    sa.Column('data_approvazione_post', sa.DateTime(), nullable=True),
    sa.Column('id_approvatore_post', sa.Integer(), nullable=True),
    sa.Column('id_dipendente', sa.Integer(), nullable=False),
    sa.Column('id_dirigente', sa.Integer(), nullable=False),
    sa.Column('stato_pre_missione', sa.String(length=50), nullable=False),
    sa.Column('data_approvazione', sa.DateTime(), nullable=True),
    sa.Column('id_approvatore_pre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_approvatore_post'], ['dipendente.id'], ),
    sa.ForeignKeyConstraint(['id_approvatore_pre'], ['dipendente.id'], ),
    sa.ForeignKeyConstraint(['id_dipendente'], ['dipendente.id'], ),
    sa.ForeignKeyConstraint(['id_dirigente'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trasferta')
    op.drop_table('delega')
    op.drop_table('dipendente')
    # ### end Alembic commands ###
