"""Add stato_approvazione_finale

Revision ID: ab09b6a6991b
Revises: 1f5f1a0efab1
Create Date: 2025-12-16 19:34:16.808599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab09b6a6991b'
down_revision = '1f5f1a0efab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stato_approvazione_finale', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('stato_approvazione_finale')

    # ### end Alembic commands ###
