"""Aggiunta tabella Spesa e campo richiesta rimborso

Revision ID: ba5b690a8515
Revises: 8958e28f86eb
Create Date: 2025-12-14 17:28:36.452185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5b690a8515'
down_revision = '8958e28f86eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_approvazione_post', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('note_approvazione_post')

    # ### end Alembic commands ###
