"""Creazione iniziale dello schema con tutti i campi

Revision ID: d50dffefd1e9
Revises: 29ab524c8a6f
Create Date: 2025-12-13 18:04:36.987693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50dffefd1e9'
down_revision = '29ab524c8a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_approvazione_pre', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_approvazione')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_approvazione', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_approvazione_pre')

    # ### end Alembic commands ###
