"""Aumentata la dimensione di password_hash a 256 caratteri per supportare hash moderni (es. scrypt).

Revision ID: fdc3a694d7f2
Revises: d50dffefd1e9
Create Date: 2025-12-13 21:33:57.804855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc3a694d7f2'
down_revision = 'd50dffefd1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dipendente', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.drop_column('temp_colonna')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trasferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_colonna', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('dipendente', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
